### ISSUE TITLE
HNN Visualize Spectrogram,Spiking - add return status, ICE Default IO Error

### ISSUE THREAD

**Issue by samnemo** [jonescompneurolab/hnn#141]
I encountered the following error (ICE default IO error handler doing an exit(), pid = 14630, errno = 32) mentioned here https://stackoverflow.com/questions/39270988/ice-default-io-error-handler-doing-an-exit-pid-errno-32-when-running/42120263
when trying to visualize spectrogram/raster from HNN. I saw the error in the terminal window but the main HNN GUI didn't report a problem. After deleting .ICeAuthority and .Xauthority files I was able to view the spectrograms from HNN. Would be good for HNN to report the error status in the GUI so the user would know status of visualization windows. And/or to deal with the IO error above automatically.

**Comment by blakecaldwell** [comment]
@samnemo This is a pretty old issue, but I was wondering if you still get this error with the latest code (just now)? Was this originally with docker or directly on Ubuntu? I've made a lot of changes to `hnn_docker.sh` so hopefully it's been resolved.

Regardless, I think letting the user know of the status once a visualization is selected is a good idea. I will consider that part of #142 when I get to fixing that. My thought is that a good time for changing this will be when we switch to hnn-core for parameter/data passing to analysis functions rather than using files.

**Comment by blakecaldwell** [comment]
Work remains to update user if one of the GUI windows fails. If there is an exception, a dialog box will be displayed, but if the newly spawned process fails, there won't be a visible error, except in the console output.

**Comment by blakecaldwell** [comment]
Closing this because the dialogs for visualizing microcircuit details have changed with #232. I don't believe the I/O error will apply since everything is done within the main python process.
