### ISSUE TITLE
Installation fails because of the Xauth issue

### ISSUE THREAD

**Issue by ka711** [jonescompneurolab/hnn#217]
Hi 
I think someone also found and solved the installation issues on windows because of the Xauth
I stuck with similar problem and was not be able to get it started
it terminated after _Copying Xauthority file into container... *failed*_

Here is my hnn_docker.log
[hnn_docker.log](https://github.com/jonescompneurolab/hnn/files/4970064/hnn_docker.log)

I would be happy to hear any suggestions!

**Comment by blakecaldwell** [comment]
@ka711 Thanks for reporting this issue! It looks like a change with the most recent version of Docker Desktop for Windows. I upgraded to version 2.3.0.4 and noticed the same thing. It'll be a few days before I can fix this for all users, but I created a quick fix that might would for you. Would you mind testing it out? The following commands will update the code in your user's `hnn/` directory.

```
git fetch origin pull/218/head:issue_217_fix
git checkout issue_217_fix
./hnn_docker.sh start
```

Once this issue is fixed (it will get closed), you can switch back to the updated master branch with:
```
git checkout master
git pull origin master
./hnn_docker.sh start
```

**Comment by ka711** [comment]
@blakecaldwell 
Hi, thank you so much for the kind fix!
I confirmed that your modified code worked well, and I successfully start the HNN!
Thank you so much and I will close this issue
