### ISSUE TITLE
View menu -> View local network (3D) problem

### ISSUE THREAD

**Issue by neuroman314** [jonescompneurolab/hnn#6]
Under Mint18.3
View menu -> View local network (3D)
elicits 
Traceback (most recent call last):
  File "visnet.py", line 2, in <module>
    import pyqtgraph as pg        
ImportError: No module named pyqtgraph

But pyqtgraph has been installed
ted@fleck ~ $ python3 -c "import pyqtgraph"
ted@fleck ~ $

**Comment by samnemo** [comment]
Was calling wrong version of Python from HNN; fixed

**Comment by axiezai** [comment]
Hi @samnemo 

I wanted to post this to the forum but the activation of my account is taking forever.

Can you clarify how you fixed these python versioning issues? I am having the same problem. I made a copy of your installer.sh file on ubuntu 16 and did 
'bash installer.sh'

I have python3 installed with conda, so I am assuming that when your .sh installer does 'sudo apt install' in line 13 it uses my native python instead of my conda's python. So when I start hnn in my terminal, and I do any visualization, it doesn't find pyqtgraph/opengl etc... 

I did a 'pip install pyqtgraph PyOpenGL' with my conda's python3, but now the hnn is complaining that there's no neuron module, and I have no idea what that is or where it is, it's obviously been installed in the wrong directory. 

Can you clarify how you fixed these old python versioning issues here?

**Comment by samnemo** [comment]
Hi Xi,

On Mon, Sep 17, 2018 at 5:27 PM Xi He <notifications@github.com> wrote:

> Hi @samnemo <https://github.com/samnemo>
>
> I wanted to post this to the forum but the activation of my account is
> taking forever.
>

Which forum did you want to join? The one at Yale (
https://www.neuron.yale.edu/phpBB/index.php) or the HNNSolver Google Group (
https://groups.google.com/forum/#!forum/hnnsolver) ? Either way, can you
provide your email address so we can get you access to the forum?

Can you clarify how you fixed these python versioning issues? I am having
> the same problem. I made a copy of your installer.sh file on ubuntu 16 and
> did
> 'bash installer.sh'
>
> I have python3 installed with conda, so I am assuming that when your .sh
> installer does 'sudo apt install' in line 13 it uses my native python
> instead of my conda's python. So when I start hnn in my terminal, and I do
> any visualization, it doesn't find pyqtgraph/opengl etc...
>
> I did a 'pip install pyqtgraph PyOpenGL' with my conda's python3, but now
> the hnn is complaining that there's no neuron module, and I have no idea
> what that is or where it is, it's obviously been installed in the wrong
> directory.
>
> Can you clarify how you fixed these old python versioning issues here?
>

Sorry for the confusion. I've cc'ed Robert McDougal who developed the
installer so he can provide suggestions for you.

Sam

**Comment by axiezai** [comment]
I applied for access to https://www.neuron.yale.edu/phpBB/index.php with the email xihe.xie@ucsf.edu

And thank you for cc-ing Robert, I look forward to hearing back from him!
